import styles from '@/styles/Home.module.css';
import { Inter } from 'next/font/google';
import Head from 'next/head';
import { Configuration, OpenAIApi } from "openai";
import { useState } from 'react';
const inter = Inter({ subsets: ['latin'] })

export async function getStaticProps() {
  const configuration = new Configuration({
    apiKey: process.env.NEXT_Open_AI_Key,
  });

  const res = JSON.stringify(configuration);

  return { props: { res } };
}

export default function Home({ res }) {
  const [prompt, setPrompt] = useState("");
  const [image, setImage] = useState<String>("");
  const [valid, setValid] = useState(true);

  const cc = JSON.parse(res);
  const openai = new OpenAIApi(cc);
  const response = async () => {
    try {
      const res = await openai.createImage({
        prompt: prompt,
        n: 1,
        size: "1024x1024",
      });
      setImage(res.data.data[0].url as String);

    } catch {
      console.log("Sorry, OpenAI denied your request. Please follow content policy.");
      setValid(false);
    }
  }

  return (
    <>
      <Head>
        <title>Create AI Image</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images.png" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <h2>Generate an Image with OpenAI API</h2>
          <input placeholder="Type something to generate an image!"
            value={prompt}
            onChange={(e) => setPrompt(e.target.value)}></input>

          <button onClick={response}>Generate</button>

          {valid ? (image.length > 0 ? <img src={image as string} alt="image" /> : <></>) : <h2>Sorry, OpenAI denied your request. Please follow content policy.</h2>}
        </div>
      </main>
    </>
  )
}
